# Generated by Django 3.1 on 2020-08-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StokAltKategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_alt_kategori', models.CharField(blank=True, max_length=255, null=True, verbose_name='urun_alt_kategori')),
            ],
            options={
                'verbose_name': 'Stok Alt Kategori',
                'verbose_name_plural': 'Stok Alt Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='StokKategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kategori', models.CharField(blank=True, max_length=255, null=True, verbose_name='urun_kategori')),
            ],
            options={
                'verbose_name': 'Stok Kategori',
                'verbose_name_plural': 'Stok Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='urun_beden_tanim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_beden_adi', models.CharField(blank=True, max_length=10, null=True, verbose_name='urun_beden_adi')),
                ('urun_beden_kisa_kodu', models.CharField(blank=True, max_length=10, null=True, verbose_name='urun_beden_kisa_kodu')),
            ],
            options={
                'verbose_name': 'Beden',
                'verbose_name_plural': 'Bedenler',
            },
        ),
        migrations.CreateModel(
            name='urun_renk_tanim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_beden_rengi', models.CharField(blank=True, default='1', max_length=10, null=True, verbose_name='urun_beden_rengi')),
            ],
            options={
                'verbose_name': 'Renk',
                'verbose_name_plural': 'Renkler',
            },
        ),
        migrations.CreateModel(
            name='Stoklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_barkod_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='urun_barkod_no')),
                ('urun_adi', models.CharField(blank=True, max_length=255, null=True, verbose_name='urun_adi')),
                ('urun_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='urun_no')),
                ('urun_fiyat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('urun_stok', models.IntegerField(blank=True, null=True, verbose_name='urun_stok_durumu')),
                ('urun_gorseli', models.FileField(blank=True, default='resimYokUrun.jpg', max_length=255, null=True, upload_to='', verbose_name='urun_gorseli')),
                ('urun_kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('urun_urun_beden_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.urun_beden_tanim')),
                ('urun_urun_rengi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.urun_renk_tanim')),
                ('urun_urun_stok_alt_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.stokaltkategori')),
                ('urun_urun_stok_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.stokkategori')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stoklar',
            },
        ),
        migrations.AddField(
            model_name='stokaltkategori',
            name='urun_urun_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.stokkategori'),
        ),
    ]
